### ISSUE TITLE
(iOS) Odd Latency Issue

### ISSUE THREAD

**Issue by Tattomoosa** [edimuj/cordova-plugin-audioinput#18]
The latency starts off at less than half a second behind, but gets worse and worse the longer the app runs.

This is without doing any processing of the audio, and I am using the default settings for audioinput.start except 'streamToWebAudio' is true.

Maybe related:

XCode logs a warning:
`2016-07-17 19:56:51.384 loops[5423:2056990] THREAD WARNING: ['AudioInputCapture'] took '373.946777' ms. Plugin should use a background thread.`

I don't need low latency for my app, but I do need predictable latency. Is there any way to accomplish that?

**Comment by edimuj** [comment]
Yeah, I know what you mean, I think the latency is introduced by the rather primitive mechanism used for sending data between the native and js layers. Using the event based method with a small buffer size and throwing new data when the data queue is larger than x, seems to be one way of getting a consistent latency. It is a bit brutal, so it may not work for all scenarios.

**Comment by edimuj** [comment]
Regarding the background thread warning: it is explained [here](http://stackoverflow.com/questions/24572174/phonegap-media-plugin-should-use-a-background-thread).

**Comment by edimuj** [comment]
I've just pushed a change that runs the result callback code in a self.commandDelegate runInBackground in iOS, should help a bit at least.
Another thing I've noticed is that the iOS UIWebView blocks js execution when scrolling, so just scrolling the page stops the JS part of this plugin which adds to latency. Could that explain the behaviour you noticed?

**Comment by Tattomoosa** [comment]
Nice! Big improvement! The initial latency is better, and i think it takes longer to drift.

XCode still logs:
`['AudioInputCapture'] took '439.781982' ms. Plugin should use a background thread.`
But since this only happens at the start and doesn't affect latency (Signal is definitely not 439ms late at first, anyway) that's probably pretty trivial.

My app is a single fullscreen page that doesn't scroll at all (I think Ionic implements its own scrolling in javascript anyway) so that shouldn't be the issue. I don't know whether any Ionic or AngularJS processes are getting in the way, either. Any thoughts on how to go about testing for that? 

The UIWebView issue does seem pretty serious, though. It stops all js execution? Are AudioNodes affected?

I think that you're initial point about the handoff is probably right-- at least larger buffer sizes definitely drift more slowly. Would it be possible/make a difference to offload some of those private/internal functions into a Worker?

I haven't had a chance to work with the event implementation you mentioned yet, but won't I basically just be copying your 'events-demo' and playing with some values? Is there a reason not to include this implementation as some sort of 'low latency' (or similar option that makes it clear that it's expensive) in the plugin proper?

Just occurred to me that we could probably hack in a failsafe using AudioContext.currentTime to line things back up by skipping samples in the buffer. Super ugly, but if the interrupts are sufficiently short, and a crossfade is implemented, it should work just fine.

**Comment by edimuj** [comment]
I agree, if the warning only appears during startup it is ok, since I believe that starting up recording is not allowed in a background thread (it must be triggered directly by a user). At least it didn't work when I tried :).

Yes, the scroll-blocks-js is not an issue on fullscreen pages and where non-native scrolling occurs, but if you for example run the demo apps for the plugin on a mobile device, the playback loop pauses when the page is scrolled. It doesn't affect Web Audio, but in this case playback stops, since the audio nodes doesn't get fed new audio buffers. I don't really know why, and haven't had any time to analyze it further, but when I run the same code in the new [WKWebView](https://github.com/apache/cordova-plugin-wkwebview-engine), the problem does not occur, so I guess that it could be anything from how the cordova native-js bridge works to something more fundamental in UIWebkit.

I like your idea of using a Worker for optimization, since that is still within the core scope of the plugin. That should improve performance a lot, and perhaps mitigate the scroll-block issue.

My original idea of this plugin was to include only the "raw" method of delivering microphone audio data, and do that well: that is the event based method. That would allow others to build extended functionality on top of that. The plugin should also be possible to use without the Web Audio API, which it still is, but I decided to add the raw data to web audio conversion anyway, since I understood that it would allow more developers to quickly get started using the plugin. So now I'm a bit irresolute about adding more complex functionality directly into the plugin core. There are so many different usage scenarios out there, so I'm afraid that by doing so, it will lead to a bloated plugin that solves many problems, but none in a good way, and at the cost of performance.

With this I don't mean that we shouldn't implement more complex functionality based on the plugin, and using AudioContext.currentTime to keep in sync and prevent drifting is really smart (I've actually already implemented a solution in another project that "stitches" separate audiobuffers by merging them together using crossfade buffers).

Maybe one idea of implementing this kind of more complex/specialized functionality is to create some kind of "Helpers" for the audioplugin... like plugins for the plugin :) These Helpers could rely on the event based method, and implement various forms of functionality that are suited for different usage scenarios: e.g. a LowLatency helper which sole purpose is to keep the audio stream in sync which is suited for apps that doesn't require 100% perfect sound, but needs the sound as near real-time as possible.

What do you think?

**Comment by edimuj** [comment]
Closing this issue, since there haven't been any activity for a while. Just give me a shout, if you want it to be reopened.

**Comment by MadyAkira** [comment]
I noticed the same issue on ios native, the first recording start instantly, only 10ms after the user pressed the recording button. 
However after the first one, the next recordings may be 10 times slower to start.

An awkward thing is that i get almost the same value each times.

Is either 10ms / 4XXms / 12XXms for each records.
Here is the logs :
```

2019-11-19 09:03:06.324079+0900 MALC[3065:252778] THREAD WARNING: ['AudioInputCapture'] took '11.770264' ms. Plugin should use a background thread.
2019-11-19 09:03:06.595259+0900 MALC[3065:252778] THREAD WARNING: ['AudioInputCapture'] took '266.926270' ms. Plugin should use a background thread.
2019-11-19 09:03:14.985693+0900 MALC[3065:252778] THREAD WARNING: ['AudioInputCapture'] took '1217.694092' ms. Plugin should use a background thread.
2019-11-19 09:03:31.758730+0900 MALC[3065:252778] THREAD WARNING: ['AudioInputCapture'] took '404.956787' ms. Plugin should use a background thread.
2019-11-19 09:03:42.077440+0900 MALC[3065:252778] THREAD WARNING: ['AudioInputCapture'] took '436.383057' ms. Plugin should use a background thread.
2019-11-19 09:03:49.849996+0900 MALC[3065:252778] THREAD WARNING: ['AudioInputCapture'] took '440.700928' ms. Plugin should use a background thread.
2019-11-19 09:04:03.143148+0900 MALC[3065:252778] THREAD WARNING: ['AudioInputCapture'] took '404.966309' ms. Plugin should use a background thread.
2019-11-19 09:04:06.864602+0900 MALC[3065:252778] THREAD WARNING: ['AudioInputCapture'] took '1233.664795' ms. Plugin should use a background thread.
2019-11-19 09:04:28.878259+0900 MALC[3065:252778] THREAD WARNING: ['AudioInputCapture'] took '1191.066406' ms. Plugin should use a background thread.
2019-11-19 09:04:37.597535+0900 MALC[3065:252778] THREAD WARNING: ['AudioInputCapture'] took '413.443848' ms. Plugin should use a background thread.
```

Maybe is there any way to clear or re-initialized audioinput value to have the same delay as the first record ?
