### ISSUE TITLE
Phonegap app not finding audio-input plugin

### ISSUE THREAD

**Issue by shahinkl** [edimuj/cordova-plugin-audioinput#38]
I have created a new phonegap project and added the cordova-plugin-audioinput plugin. Then I copied the demo folder from the plugin to _www_ directory of the phonegap app. When I tried running the demos, I am getting the warning 'cordova-plugin-audioinput not found!'. Any help would be greatly appreciated to resolve my issue.

**Comment by shahinkl** [comment]
When tried in the web context getting below error.

onAudioInputError event recieved: {"isTrusted":false,"message":"Missing Command Error"}

**Comment by edimuj** [comment]
Sounds like somethings doesn't get initialized correctly, but I need to see your project in order to help you.

**Comment by shahinkl** [comment]
[https://github.com/shahinkl/krypto-sr-mobile/blob/master/www/lib/app/js/wave.js](url)

**Comment by shahinkl** [comment]
Thanks You
Please check the wave.js file

[wave.js.zip](https://github.com/edimuj/cordova-plugin-audioinput/files/853331/wave.js.zip)

**Comment by edimuj** [comment]
Hi, thanks, I looked at the wave.js file, but I cannot see what goes wrong based on that file only, since it is basically just a stripped down version of the demo in this project. 

Would need the entire context in which that file is used: Your full Apache Cordova project, i.e. including the config.xml, index.html etc., would make it easier to see where something goes wrong during the app startup and initialization. When I test the plugin with the demo on real iOS and Android devices, I don't get the "Missing Command Error". That particular error indicates that the plugin has been installed on a non-supported device, for which this plugin doesn't have native code, and the other error "cordova-plugin-audioinput not found!" does indicate that the plugin hasn't been installed properly.

How do you run your project, in the browser, simulator or on a device (brand/model, OS and OS version is then interesting to know)? And a more complete project would also be good to look at.

**Comment by edimuj** [comment]
I found your project based on the URL you posted above.. the URL it points to is wrong https://github.com/shahinkl/krypto-sr-mobile/blob/master/www/lib/app/js/wave.js -> "https://github.com/edimuj/cordova-plugin-audioinput/issues/url". I'll take a look at it.

**Comment by shahinkl** [comment]
Thank you! I am glad to receive your help.

**Comment by shahinkl** [comment]
I got the error while running on my android/iOS devices.

**Comment by edimuj** [comment]
I'm sorry for the late reply, I just can't see why you get the missing command error. I just tried the plugin on a Nexus 5X with Android 7.1.2 and it works correctly. What Android and iOS devices and OS versions do you use to test your app? Does the app have permission to record audio on your devices?

**Comment by edimuj** [comment]
Doing some housekeeping: Since there hasn't been any action regarding this issue for a time now, I'm closing it.
