### ISSUE TITLE
Capturing android speaker output ?!

### ISSUE THREAD

**Issue by doonfrs** [edimuj/cordova-plugin-audioinput#44]
Hi;
I am asking if it is possible per your experience to use android speaker output as 'input' for the steam.
I saw an application doing this already, but I am wondering if it is possible? I can fork it for this feature but I want to discuss it first.

Thank you!

**Comment by edimuj** [comment]
Sorry, I haven't any experience of that. Is it something for capturing speaker sounds directly instead of through the mic, like for call recording? Anyway, sounds like a cool feature, as long as it doesn't get confusing when using the plugin in an app for both Android and iOS. Perhaps the speaker input could be specified as an additional AudioSourceType?

**Comment by GabrielVanderlei** [comment]
I have this question too. Its like capture the áudio of a sound playing at the background (the origin its an another app).

**Comment by edimuj** [comment]
Since there haven't been any activity on this issue for some time, I'm closing it. If there is more information, feel free to open it again.
