### ISSUE TITLE
what is normalizationFactor

### ISSUE THREAD

**Issue by zyf0330** [edimuj/cordova-plugin-audioinput#9]
Could you explain normalizationFactor for me? and why to enable normalize

**Comment by zyf0330** [comment]
Maybe it can adjust loudness of sound?
But how to save it as file?

**Comment by edimuj** [comment]
The normalize option is used to convert the raw audio data samples from the byte values that are captured to floating point values. For 16 bit data the value range is +/-32767 and therefore each sample should be divided by 32767 in order to get something between -1.0 and +1.0. The main reason to use normalize is that the Web Audio API plays nice with float data, but you don't need to use the Web Audio API you can turn off the normalize option.

Loudness
Yes, you can adjust the loudness of the sound by multiplying each sample with a factor (e.g.  sample value * 1.2), but this will most probably lead to clipping (values over 1.0 cannot be played over the speakers). So it is probably better to use the Web Audio API if you want to adjust the loudness (gain node + compressor node is a good combination). If you don't want or can use the WAAPI, there are algorithms that can be used to convert the audio, that are more advanced than my simple example above. [pcm-volume](https://github.com/reneraab/pcm-volume) for example.

Saving to File
Can be done in numerous ways, depending on your specific application. One option is: [web-audio-recorder-js](https://github.com/higuma/web-audio-recorder-js) or a similar lib with or without the [Cordova File plugin](https://github.com/apache/cordova-plugin-file) for saving the actual file.

**Comment by zyf0330** [comment]
I have learned about [saveToWAV](https://github.com/higuma/wav-audio-encoder-js). But it is not successful. I use params `{normalize: false, channels: 1, sampleRate: 44100, format: 'PCM_16BIT'}` to get audio data array, and give it to wav-audio-encoder, but get a bad wav file. Why?

**Comment by edimuj** [comment]
Looks like [saveToWav](https://github.com/higuma/wav-audio-encoder-js) wants a normalized buffer:

`encoder.encode(buffers)`

"buffers **must be an array of Float32Array audio data (range = [-1, 1])**. Array length must be same as number of channels. It supports stream (incremental) processing. Sample buffers are processed to .wav fragment and appended to internal data."

So I would instead use the following configuration for the plugin:
`{normalize: true, channels: 1, sampleRate: 44100, format: 'PCM_16BIT'}`

You'd then get a buffer with float samples ranging from -1.0 to +1.0, which seems to be what the saveToWAV encoder method wants.

**Comment by zyf0330** [comment]
Sorry, I say something wrong. I also attempt `normalize: true`, and in fact, I know most principles of it, but still fail.

**Comment by edimuj** [comment]
Do you have some code here in github that I could take a look at?

**Comment by zyf0330** [comment]
I just use your module to get data and pass into that encoder like bottom:
these are some pieces code.
```
window.addEventListener("audioinput", function (event) {
					data = data.concat(event.data);
				}, false);
```
```
cfg: {
					sampleRate: 44100,
					bufferSize: 16384,
					channels: 1,
					format: 'PCM_16BIT',
					normalize: true,
					normalizationFactor: 32767.0,
					streamToWebAudio: false,
					concatenateMaxChunks: 10
				},
```
```
var e = new WavAudioEncoder(44100, 1);
e.encode([data]);
e.finish();
```

**Comment by edimuj** [comment]
Thanks, I will check this out in a test project. Will update you on the progress.

**Comment by zyf0330** [comment]
another thing, `_normalize` function will return string array, so maybe `inputaudiodata` should be parsed by `JSON.parse` to get int array.

**Comment by edimuj** [comment]
The _normalize function returns an array of floats. The audioInputEvent function gets a comma-separated string from the native layer of the plugin, which is converted to an int array with samples. If normalize is used, the samples are converted to floats.

**Comment by edimuj** [comment]
I looked into it and got it to work with [WavAudioEncoder.js](https://github.com/higuma/wav-audio-encoder-js) which previously was mentioned as saveToWav.

Start capturing using the defaults:
```
audioinput.start();
```

Gather the incoming data in the audioinput event listener:
`audioDataBuffer = audioDataBuffer.concat(evt.data);`

And when capture is stopped:
```
// Use WavAudioEncoder.js to encode the captured array to a blob
var encoder = new WavAudioEncoder(44100, 1);
encoder.encode([audioDataBuffer]);
var blob = encoder.finish("audio/wav");

// To be able to load the blob on a device, we use a HTML5 FileReader
var reader = new FileReader();

reader.onload = function(evt){
 // When blob has been loaded, create an audio element for it
 var audio = document.createElement("AUDIO");
 audio.controls = true;
 audio.src = evt.target.result;
 audio.type = "audio/wav";

 // Add the new audio element to the page, so that the user can play it
 document.getElementById("recording").appendChild(audio);
};

// Start loading the blob
reader.readAsDataURL(blob);
```

The blob can, of course, also be saved as file using cordova-plugin-file or uploaded somewhere etc.

**Comment by zyf0330** [comment]
I have found the problem, it appears when saveToFile. I use cordova-plugin-file to get FileEntry and save blob by `FileEntry.createWriter().write`, and everything is ok, but I get a bad file. If I change the blob to dataurl, it works normally.

**Comment by edimuj** [comment]
I have created an example (demos folder) of saving audio to file using the Cordova file plugin, and will push it next week. Thanks for all the help with this.

**Comment by zyf0330** [comment]
@edimuj I found that wav can play on my computer, but Android cannot with play music or RE music etc.
It is funny, do you know?

**Comment by zyf0330** [comment]
@edimuj I know why, I save that file into internal storage of app, and other app has no permission to read it. Sorry.

**Comment by edimuj** [comment]
I agree, that is not so easy to know. I think that the behaviour of the cordova file plugin in general is pretty confusing.

**Comment by zyf0330** [comment]
Whatever, I just convert it into dataurl now to play it. And remain issue to them.

**Comment by edimuj** [comment]
Good!
